runtime: python39
env: flex

env_variables:
  HOST: '0.0.0.0'

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  cool_down_period_sec: 180